### ISSUE TITLE
 "PublishSelectedPoints" in RViz  [deep_learning/auto_recognition2/src/selectArea.cpp]

### ISSUE THREAD

**Issue by aaronhd** [ZhiangChen/deep_learning#1]
Hi Chen,  
I am very interested in your 'deep_learning/auto_recognition2', so I try to realize it again by myself. I used ros kinetic, and rviz can only publish single point. I want to know if you used a plugin in rviz or other method to send the selected area points.

Thank you!

**Comment by ZhiangChen** [comment]
Hi, 

Thanks for your interest! I did use a plugin in rviz - rviz_plugin_selected_points_topic. You can find it at my another repo: https://github.com/ZhiangChen/nw_ros/, which was adapted from Wyatt's [learning_ros](https://github.com/wsnewman/learning_ros). According to my previous experience, this plugin that was developed on ros indigo doesn't support kinetic. But the point is this package is used for figuring out the position and orientation (or tf) of a box on a table, so maybe you can try other methods. Good luck to your work! And please let me know if you figure out any solutions. Thanks!

**Comment by aaronhd** [comment]
@ZhiangChen   Thank you for your help, I have fixed the problem. But it just works on indigo, and cannot work on kinect(same rospackage but have core dump problem). Have you meet some incompatibility problems in using tensorflow(anaconda enviroment) and ros?

**Comment by ZhiangChen** [comment]
I assume you meant kinetic, on which the publish-selected-points plugin DOES NOT support. (please refer to my previous reply.) I didn't use anaconda environment and haven't met any incompatibility problems with tensorflow and ros. Just make sure that you use python2 instead of python3 that doesn't support rospy.
